### ISSUE TITLE
Crash when git repo has no master branch

### ISSUE THREAD

**Issue by mezz** [tomasbjerre/git-changelog-lib#28]
Hello, I'm trying to add git-changelog to my project.
My project does not have a `master` branch. I use version branches.
I get this crash when I run it: https://gist.github.com/mezz/b7efe8e440acc82105486c72c9dc5158

This seems to requite a master branch:
https://github.com/tomasbjerre/git-changelog-lib/blob/master/src/main/java/se/bjurr/gitchangelog/internal/git/GitRepo.java#L314-L315

Here is my project: https://github.com/mezz/JustEnoughItems

I tried setting `fromCommit` to my first commit sha but it still crashes the same way.

**Comment by mezz** [comment]
Found a workaround: tagged the first commit as "master"

**Comment by tomasbjerre** [comment]
Fixed in 1.49

**Comment by coderzh** [comment]
Can't work when has no master branch. I use jenkins changelog plugin, output is:

```
---
--- Git Changelog ---
---
se.bjurr.gitchangelog.api.exceptions.GitChangelogRepositoryException: 
	at se.bjurr.gitchangelog.internal.git.GitRepo.getRef(GitRepo.java:124)
	at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:384)
	at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:352)
	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:371)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:130)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:29)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at hudson.remoting.Engine$1$1.run(Engine.java:69)
	at java.lang.Thread.run(Thread.java:744)

**Comment by tomasbjerre** [comment]
What version of the jenkins plugin do you use? This should have been fixed in 1.28.

**Comment by coderzh** [comment]
1.28

**Comment by tomasbjerre** [comment]
Can you post a screenshot of your config?
Den 24 jun 2016 08:30 skrev "coderzh" <notifications@github.com>:

**Comment by mezz** [comment]
The git tag and your post from earlier state that this was fixed in 1.49. Why do you both say 1.28?

**Comment by tomasbjerre** [comment]
This is just the library. The plugin is another project.

**Comment by coderzh** [comment]
![](http://7xlx3k.com1.z0.glb.clouddn.com/changelog.png)

FROM_REVISION and TO_REVISION are String Parameters

**Comment by coderzh** [comment]
The more pain about this plugin is that, when merged from other branch, it do not show the commits merged from that branch. (Jenkins Git Plugin's changelog seems can do that).

**Comment by tomasbjerre** [comment]
Looks like this is causing the behavior:
```
  ObjectId toId = getId(gitRepo, settings.getToRef(), settings.getToCommit()) //
    .or(gitRepo.getRef(REF_MASTER));
```
Which means it cant find a value for *to reference* or *to commit*, so it defaults back to *master*.  You may print ${TO_REVISION} in a shell build step, to see make sure it does not resolve to an empty string.

You will have to be more specific about you merge issue. You need to supply output of:
```
git log --graph --full-history --all --color --date=short --pretty=format:"%Cred%x09%h %Creset%ad%Cgreen%d %Creset %s %C(bold)(%an)%Creset"
```
And the value of *from* and *to*.

**Comment by coderzh** [comment]
The revision is really exists and right. Not empty string.

**Comment by coderzh** [comment]
I will add a merge issue next time. Thanks very much!

**Comment by tomasbjerre** [comment]
What happens if you hard code a hash in the "to" field, just for testing. Does that work?

**Comment by tomasbjerre** [comment]
I created https://github.com/tomasbjerre/git-changelog-lib/issues/29 for the merge issue... help is welcome =)

**Comment by tomasbjerre** [comment]
Did you try to hard code the "to" hash?

**Comment by coderzh** [comment]
I am outside now, i will try to hard code next time. But I think String Parameter is not the problem, because it works when i create the master branch.

**Comment by tomasbjerre** [comment]
Perhaps you did not clone with all refs? What if you `cd` into the jenkins workspace of that job and do `grep -RnH "X" .git/*` where X is the ref you are expect to exist. Is it found there?

**Comment by tomasbjerre** [comment]
@coderzh I added better logging for this also. So the error now contains the references that were found. To help track down the problem. Its in the Jenkins plugin v1.30.

**Comment by coderzh** [comment]
I updated the new Jenkins plugin v1.32. There is no master in the ref list log.

Finally, i added shell script `git checkout -b master` to create local master, then it works.

Many thanks!

**Comment by swetha2598** [comment]
hgetting this error @tomasbjerre can u help me resolve it
--- Git Changelog ---
---
java.lang.RuntimeException: Cannot find on classpath (changelog.mustache) or filesystem (/data/nelsonrajj/jenkins/workspace/changelog.mustache).
	at se.bjurr.gitchangelog.api.GitChangelogApi.getTemplateContent(GitChangelogApi.java:502)
	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:94)
	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:123)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:150)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:27)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: changelog.mustache (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.google.common.io.Files$1.getInput(Files.java:105)
	at com.google.common.io.Files$1.getInput(Files.java:102)
	at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:249)
	at com.google.common.io.Files.toByteArray(Files.java:197)
	at com.google.common.io.Files.toString(Files.java:223)
	at se.bjurr.gitchangelog.api.GitChangelogApi.getTemplateContent(GitChangelogApi.java:496)
	... 12 more
